# This is a basic workflow to help you get started with Actions

name: Build Release Notes

# Controls when the action will run. 
on: [pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Create Release Notes
        uses: Kellojo/github-release-notes-generator@v1.4
        with:
          destination: './webapp/config/release-notes.json'
          github-access-token: ${{ secrets.github_token }}
          
      - uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'Built release notes'
          add: '*.json'
