# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:    
      - name: Check out Git repository
        uses: actions/checkout@v1
        with:
          submodules : true 

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10
          
      - name: Delete current release assets
        uses: Kellojo/delete-release-assets-action@v1.8
        with:
          delete-only-drafts: true
          github-access-token: ${{ secrets.github_token }}
      - name: Create Release Notes
        uses: Kellojo/github-release-notes-generator@v1
        with:
          destination: './webapp/config/release-notes.json'
          github-access-token: ${{ secrets.github_token }}

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1.1
        env:
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          APPLE_NOTARIZE_ID: ${{ secrets.APPLE_NOTARIZE_ID }}
          APPLE_NOTARIZE_PASSWORD: ${{ secrets.APPLE_NOTARIZE_PASSWORD }}
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
